# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates CLAUDE.md optimized for Claude Code.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with behavioral rules.
    class ClaudeSerializer
      include TestCommandDetection
      include StackOverviewHelper
      include DesignSystemHelper

      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullClaudeSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_ui_patterns)
        lines.concat(render_mcp_guide)
        lines.concat(render_conventions)
        lines.concat(render_commands)
        lines.concat(render_footer)

        # Enforce max lines
        max = RailsAiContext.configuration.claude_max_lines
        if lines.size > max
          lines = lines.first(max - 2)
          lines << ""
          lines << "_Context trimmed. Use MCP tools for full details._"
        end

        lines.join("\n")
      end

      def render_header
        [
          "# #{context[:app_name]} — AI Context",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-context v#{RailsAiContext::VERSION}",
          ""
        ]
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        schema = context[:schema]
        if schema && !schema[:error]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
        end

        models = context[:models]
        if models.is_a?(Hash) && !models[:error]
          lines << "- Models: #{models.size}"
        end

        routes = context[:routes]
        if routes && !routes[:error]
          # Count only app controllers (exclude internal Rails, Devise, Turbo routes)
          internal = %w[action_mailbox/ active_storage/ rails/ conductor/ devise/ turbo/]
          app_ctrls = (routes[:by_controller] || {}).keys.reject { |k| internal.any? { |p| k.downcase.start_with?(p) } }
          lines << "- Routes: #{routes[:total_routes]} across #{app_ctrls.size} controllers"
        end

        jobs = context[:jobs]
        if jobs.is_a?(Hash) && !jobs[:error]
          job_count = jobs[:jobs]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << "#{job_count} jobs" if job_count > 0
          parts << "#{mailer_count} mailers" if mailer_count > 0
          parts << "#{channel_count} channels" if channel_count > 0
          lines << "- Async: #{parts.join(', ')}" if parts.any?
        end

        migrations = context[:migrations]
        if migrations.is_a?(Hash) && !migrations[:error]
          pending = migrations[:pending]
          lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
        end

        lines.concat(full_preset_stack_lines)

        lines << ""
        lines
      end

      def render_key_models
        models = context[:models]
        return [] unless models.is_a?(Hash) && !models[:error] && models.any?

        max_show = 15
        lines = [ "## Key models (#{models.size} total)" ]
        models.keys.sort.first(max_show).each do |name|
          data = models[name]
          assoc_count = (data[:associations] || []).size
          val_count = (data[:validations] || []).size
          top_assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
          scopes = (data[:scopes] || [])
          constants = (data[:constants] || [])
          if scopes.any? || constants.any?
            extras = []
            extras << "scopes: #{scopes.join(', ')}" if scopes.any?
            constants.each { |c| extras << "#{c[:name]}: #{c[:values].join(', ')}" }
            lines << "  #{extras.join(' | ')}"
          end
        end
        lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
        lines << ""
        lines
      end

      def render_notable_gems
        gems = context[:gems]
        return [] unless gems.is_a?(Hash) && !gems[:error]
        notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_architecture
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []
        return [] if arch.empty? && patterns.empty?

        arch_labels = RailsAiContext::Tools::GetConventions::ARCH_LABELS rescue {}
        pattern_labels = RailsAiContext::Tools::GetConventions::PATTERN_LABELS rescue {}

        lines = [ "## Architecture" ]
        arch.each { |p| lines << "- #{arch_labels[p] || p}" }
        patterns.first(8).each { |p| lines << "- #{pattern_labels[p] || p}" }

        # List service objects and jobs from conventions directory_structure
        dir_struct = conv[:directory_structure] || {}

        if dir_struct["app/services"]
          begin
            root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
            service_files = Dir.glob(File.join(root, "app", "services", "*.rb"))
              .map { |f| File.basename(f, ".rb").camelize }
              .reject { |s| s == "ApplicationService" }
            lines << "" << "**Services:** #{service_files.join(', ')}" if service_files.any?
          rescue; end
        end

        if dir_struct["app/jobs"]
          begin
            root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
            job_files = Dir.glob(File.join(root, "app", "jobs", "*.rb"))
              .map { |f| File.basename(f, ".rb").camelize }
              .reject { |j| j == "ApplicationJob" }
            lines << "**Jobs:** #{job_files.join(', ')}" if job_files.any?
          rescue; end
        end

        lines << ""
        lines
      end

      def render_ui_patterns
        render_design_system(context, max_lines: 30)
      end

      def render_mcp_guide # rubocop:disable Metrics/MethodLength
        [
          "## MCP Tools (25) — ALWAYS Use These First",
          "",
          "This project has live MCP tools. You MUST use them instead of reading reference files.",
          "Start with `detail:\"summary\"`, then drill into specifics.",
          "",
          "### Mandatory Workflow",
          "1. **Before exploring a feature**: `rails_analyze_feature(feature:\"...\")` — NOT Explore agents or Grep",
          "2. **Before writing migrations**: `rails_get_schema(table:\"...\")` — NOT reading db/schema.rb",
          "3. **Before modifying a model**: `rails_get_model_details(model:\"...\")` — NOT reading the model file",
          "4. **Before adding routes**: `rails_get_routes(controller:\"...\")` — Read routes.rb only when you will edit it",
          "5. **Before creating views**: `rails_get_design_system` — match existing patterns",
          "6. **After editing ANY file**: `rails_validate(files:[...])` — no exceptions, no ruby -c / erb / node -c",
          "",
          "### Quick Reference",
          "| Need | Use this MCP tool | Do NOT use |",
          "|------|-------------------|------------|",
          "| Column types | `rails_get_schema(table:\"x\")` | Read db/schema.rb |",
          "| Model associations | `rails_get_model_details(model:\"X\")` | Read app/models/x.rb |",
          "| Route paths | `rails_get_routes(controller:\"x\")` | Read config/routes.rb |",
          "| Feature overview | `rails_analyze_feature(feature:\"x\")` | Explore agent / Grep |",
          "| Find code | `rails_search_code(pattern:\"x\")` | Grep tool |",
          "| Validate edits | `rails_validate(files:[...])` | ruby -c / erb / node |",
          "| Controller logic | `rails_get_controllers(controller:\"X\", action:\"y\")` | Read controller file |",
          "| UI patterns | `rails_get_design_system` | Read view files |",
          "| Stimulus API | `rails_get_stimulus(controller:\"x\")` | Read JS files |",
          "| Test patterns | `rails_get_test_info(model:\"X\")` | Read test files |",
          "| Full context | `rails_get_context(model:\"X\")` | Multiple Read calls |",
          "",
          "### More Tools",
          "- `rails_get_view(controller:\"x\")` | `rails_get_concern(name:\"X\")` | `rails_get_callbacks(model:\"X\")`",
          "- `rails_get_helper_methods` | `rails_get_service_pattern` | `rails_get_job_pattern`",
          "- `rails_get_env` | `rails_get_partial_interface(path:\"shared/_form\")` | `rails_get_turbo_map`",
          "- `rails_get_config` | `rails_get_gems` | `rails_get_conventions` | `rails_security_scan`",
          "- `rails_get_edit_context(file:\"path\", near:\"keyword\")` — surgical edit helper with line numbers",
          ""
        ]
      end

      def render_conventions
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        config_files = conv[:config_files] || []
        return [] if config_files.empty?

        lines = [ "## Key config files" ]
        config_files.first(5).each { |f| lines << "- `#{f}`" }
        lines << ""
        lines
      end

      def render_commands
        test_cmd = detect_test_command
        [
          "## Commands",
          "- `bin/dev` — start dev server",
          "- `#{test_cmd}` — run tests",
          "- `rails db:migrate` — run pending migrations",
          ""
        ]
      end

      def render_footer
        [
          "## Rules",
          "- Follow existing patterns and conventions",
          "- Match existing code style",
          "- Run tests after changes",
          "- After editing, ALWAYS use `rails_validate(files:[...])` — do NOT use separate ruby -c / erb / node -c calls",
          "- Do NOT re-read files to verify edits — trust your Edit, validate syntax only",
          "- Stimulus controllers auto-register — no manual import in controllers/index.js needed",
          "",
          "## MCP-First Rule — Do NOT Bypass",
          "- Do NOT read db/schema.rb — use `rails_get_schema`",
          "- Do NOT read config/routes.rb for reference — use `rails_get_routes`",
          "- Do NOT read model files for associations/scopes — use `rails_get_model_details`",
          "- Do NOT use Grep to search code — use `rails_search_code`",
          "- Do NOT launch Explore agents for context — use `rails_analyze_feature`",
          "- Do NOT read test files for patterns — use `rails_get_test_info`",
          "- Read files ONLY when you are about to Edit them",
          ""
        ]
      end
    end

    # Internal: full-mode Claude serializer (wraps MarkdownSerializer with behavioral rules)
    class FullClaudeSerializer < MarkdownSerializer
      include TestCommandDetection

      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives Claude Code deep context about this Rails application's
          structure, patterns, and conventions. Use it to write idiomatic code
          that matches this project's style.
        MD
      end

      def footer
        rules = []
        rules << "## Behavioral Rules"
        rules << ""
        rules << "When working in this codebase:"
        rules << "- Follow existing patterns and conventions detected above"
        rules << "- Use the database schema as the source of truth for column names and types"
        rules << "- Respect existing associations and validations when modifying models"
        rules << "- Match the project's architecture style (#{architecture_summary})" if architecture_summary
        test_cmd = detect_test_command
        rules << "- Run `#{test_cmd}` after making changes to verify correctness"
        rules << ""
        rules << super
        rules.join("\n")
      end

      def architecture_summary
        arch = context.dig(:conventions, :architecture)
        arch&.any? ? arch.join(", ") : nil
      end
    end
  end
end
